USE `ebenta`;

-- 1. Update all users' address, city, province, and postal code to San Carlos City, Pangasinan (2420)
UPDATE `ebenta`.`users`
SET 
    `address_city` = 'San Carlos City',
    `address_province` = 'Pangasinan',
    `postal_code` = '2420',
    `barangay` = CASE (id % 30)
        WHEN 0 THEN 'Palaris'
        WHEN 1 THEN 'Rizal'
        WHEN 2 THEN 'Mabini'
        WHEN 3 THEN 'Bugallon-Posadas'
        WHEN 4 THEN 'Lucban'
        WHEN 5 THEN 'Padilla'
        WHEN 6 THEN 'Talang'
        WHEN 7 THEN 'Coliling'
        WHEN 8 THEN 'Turac'
        WHEN 9 THEN 'Agdao'
        WHEN 10 THEN 'Abanon'
        WHEN 11 THEN 'Bocboc'
        WHEN 12 THEN 'Mamarlao'
        WHEN 13 THEN 'Tarece'
        WHEN 14 THEN 'Magtaking'
        WHEN 15 THEN 'Baldog'
        WHEN 16 THEN 'Pagal'
        WHEN 17 THEN 'Capandanan'
        WHEN 18 THEN 'Balococ'
        WHEN 19 THEN 'Tamayo'
        WHEN 20 THEN 'Tandoc'
        WHEN 21 THEN 'Caoayan Kiling'
        WHEN 22 THEN 'Ilang'
        WHEN 23 THEN 'San Pedro-Taloy'
        WHEN 24 THEN 'Antipangol'
        WHEN 25 THEN 'Bacnar'
        WHEN 26 THEN 'Balite Sur'
        WHEN 27 THEN 'Bega'
        WHEN 28 THEN 'Dalandan'
        ELSE 'Gamata'
    END,
    `address_line_1` = CASE (id % 30)
        WHEN 0 THEN '14 Palaris Street'
        WHEN 1 THEN '88 Rizal Avenue'
        WHEN 2 THEN '25 Perez Boulevard'
        WHEN 3 THEN '42 Mabini Street'
        WHEN 4 THEN '52 Bugallon-Posadas Street'
        WHEN 5 THEN '19 Montemayor Street'
        WHEN 6 THEN '31 Gomez Street'
        WHEN 7 THEN '76 Roxas Boulevard'
        WHEN 8 THEN 'Purok 1, San Carlos-Calasiao Road'
        WHEN 9 THEN 'Purok 2, San Carlos-Calasiao Road'
        WHEN 10 THEN 'Purok 3, San Carlos-Malasiqui Road'
        WHEN 11 THEN 'Purok 4, San Carlos-Malasiqui Road'
        WHEN 12 THEN 'Purok 1, San Carlos-Aguilar Road'
        WHEN 13 THEN 'Purok 2, San Carlos-Basista Road'
        WHEN 14 THEN 'Sitio Centro, Coliling Road'
        WHEN 15 THEN 'Purok 4, Turac Highway'
        WHEN 16 THEN 'Purok 1, Agdao Proper'
        WHEN 17 THEN 'Sitio Riverside, Abanon'
        WHEN 18 THEN 'Purok 3, Bocboc Proper'
        WHEN 19 THEN 'Block 5 Lot 12, Villa San Carlos Subd.'
        WHEN 20 THEN 'Block 2 Lot 8, Doña Maria Subdivision'
        WHEN 21 THEN 'Block 9 Lot 14, San Carlos Heights'
        WHEN 22 THEN 'Purok 5, Tarece Road'
        WHEN 23 THEN 'Sitio Centro Norte, Pagal'
        WHEN 24 THEN 'Purok 1, Capandanan'
        WHEN 25 THEN 'Purok 3, Balococ'
        WHEN 26 THEN 'Purok 6, Tamayo Road'
        WHEN 27 THEN 'Purok 2, Tandoc'
        WHEN 28 THEN 'Purok 4, Caoayan Kiling'
        ELSE 'Purok 2, Baldog'
    END;

-- 2. Update all sellers to authentic San Carlos City & Pangasinan circular technology businesses
UPDATE `ebenta`.`users`
SET
    `business_name` = CASE (id % 20)
        WHEN 0 THEN 'San Carlos Tech Recovery & E-Scrap Solutions'
        WHEN 1 THEN 'Palaris Component Traders & Computer Salvage'
        WHEN 2 THEN 'Binalatongan Hardware Exchangers'
        WHEN 3 THEN 'Pangasinan Green Silicon & Laptop Depot'
        WHEN 4 THEN 'Agdao Computer Parts & E-Waste Exchange'
        WHEN 5 THEN 'Central Pangasinan Tech Recyclers'
        WHEN 6 THEN 'Turac Electronics Salvage & Refurbishment'
        WHEN 7 THEN 'Rizal Avenue MicroTech Solutions'
        WHEN 8 THEN 'Pangasinan Circular Hardware Trading'
        WHEN 9 THEN 'San Carlos EcoByte Component Center'
        WHEN 10 THEN 'North Luzon E-Scrap Depot - San Carlos Branch'
        WHEN 11 THEN 'Coliling Tech Scrap & Circuit Lab'
        WHEN 12 THEN 'Mabini Computer Salvage & Parts Hub'
        WHEN 13 THEN 'Pangasinan E-Benta Salvage Center'
        WHEN 14 THEN 'San Carlos CircuitWorks & Hardware Recovery'
        WHEN 15 THEN 'Perez Blvd. Digital Scrap & Refurbishing'
        WHEN 16 THEN 'Talang Green Hardware Trading'
        WHEN 17 THEN 'Pangasinan Silicon Cycle Workshop'
        WHEN 18 THEN 'Bugallon-Posadas Tech Salvage'
        ELSE 'Bocboc Electronic Waste & Scrap Hub'
    END,
    `business_description` = CASE (id % 20)
        WHEN 0 THEN 'Leading Pangasinan e-waste collection center specializing in circuit board recovery, tested repairable units, and eco-friendly component disposal in San Carlos City.'
        WHEN 1 THEN 'Trusted San Carlos City scrap and hardware trading hub. We buy salvage laptops, server racks, and office desktop units across central Pangasinan.'
        WHEN 2 THEN 'Historic Binalatongan circular tech dealer providing tested motherboards, refurbished power supplies, and component-level electronics recycling.'
        WHEN 3 THEN 'Eco-certified electronics refurbishment workshop in San Carlos City. Specializing in corporate laptop upgrades, RAM/SSD harvesting, and scrap salvage.'
        WHEN 4 THEN 'Community e-waste drop-off and component salvage partner in San Carlos City, Pangasinan. Promoting circular electronics since 2023.'
        WHEN 5 THEN 'Bulk e-waste aggregators serving San Carlos City, Calasiao, and Malasiqui. Licensed electronic scrap recovery and eco-footprint reporting.'
        WHEN 6 THEN 'Harvesting functional chips, screens, and copper components from decommissioned office tech in San Carlos City.'
        WHEN 7 THEN 'Downtown San Carlos City computer repair, display panel reclamation, and responsible e-waste dismantling facility.'
        WHEN 8 THEN 'Purchasing bulk salvage, repairable PCs, and defective electronics for sustainable recovery across the province of Pangasinan.'
        WHEN 9 THEN 'Certified repair and electronics recycling facility in San Carlos City. Refurbishing business-grade ThinkPads, monitors, and harvested parts.'
        WHEN 10 THEN 'Regional tech recycling point handling municipal and commercial e-scrap, power supplies, and printed circuit board segregation.'
        WHEN 11 THEN 'Specialized component testing, solder reclamation, and safe battery disposal in San Carlos City, Pangasinan.'
        WHEN 12 THEN 'Local San Carlos tech recycler providing tested working processors, power adapters, and certified eco-disposal.'
        WHEN 13 THEN 'Dedicated platform seller for recovered electronic components, salvage bulk lots, and certified green recycling certificates.'
        WHEN 14 THEN 'Professional hardware triage, logic board component harvesting, and green electronics supply for Pangasinan.'
        WHEN 15 THEN 'San Carlos City center for tested DDR3/DDR4 memory, refurbished LCD displays, and safe e-waste segregation.'
        WHEN 16 THEN 'Eco-conscious e-waste trader and parts reclaimer serving San Carlos City and nearby Pangasinan municipalities.'
        WHEN 17 THEN 'Transforming discarded corporate tech and scrap electronics into tested, reusable computer hardware in San Carlos City.'
        WHEN 18 THEN 'Poblacion-based e-waste recovery shop buying decommissioned office desktops, laptop batteries, and copper wiring.'
        ELSE 'Licensed electronics dismantler and circular materials vendor operating in San Carlos City, Pangasinan.'
    END
WHERE `role` = 'seller';
